### ISSUE TITLE
Can somebody Elaborate more on MQTT connector

### ISSUE THREAD

**Issue by Tatya-winchu** [OpenMTC/OpenMTC#11]
I have mosquitto broker sunning on local system and I wish to see the sensor data on openMTC. I am unable to understand the process described in mqtt connector section. I can publish data on broker, but unable to proceed towards openMTC connector. please guide
Thank you

**Comment by ckl-fokus** [comment]
Hi @kedardahivale ,

Please tell me how you have started your setup and on which Topics you publish data on your Mosquitto broker.

**Comment by ckl-fokus** [comment]
Hi @kedardahivale,

Are you still interested, or can I close the issue?
