### ISSUE TITLE
where to find Add-ons code for IPEs annonced in web site

### ISSUE THREAD

**Issue by agaldemas** [OpenMTC/OpenMTC#13]
Hello,
in the site openmtc.org, on platform page, are listed the following Protocol Adapters (IPE) Add-ons :
- ZigBee for Smart Building
- PROFINET and Modbus for Industry 4.0
- OPC-UA client
- Robot OS (ROS)
I can't find any repository for those add-ons on github, it doesn't seem to be included in this openmtc repository, hence can you tell me if those add-ons are available or not, in case they are wher to find it ?
Thanks in advance for your answer

**Comment by ckl-fokus** [comment]
Hi,

The IPEs you mentioned are not part of our opensource base. But there are possibilities for licensed use. If you are interested in that, please contact us via info@openmtc.org

**Comment by agaldemas** [comment]
OK, thanks for your answer

**Comment by agaldemas** [comment]
I'll contact you through the given email address
