### ISSUE TITLE
$ ./create-binary-docker Not working on OSX

### ISSUE THREAD

**Issue by ilovetogetspamed** [OpenMTC/OpenMTC#16]
```
$ ./create-binary-docker gateway
Error: Exactly one module name needs to be provided
Usage: create-binary-docker [OPTS] <module_name>
  OPTS:
    -a|--arch <ARCH>           Choose architecture: amd64|arm
    -p|--prefix <Name Prefix>  Choose Docker image name prefix
    -e|--export                Export the Docker image to a file, after build

    -h|--help                  Show this help
    -v|--version               Show version information

  module_name:
    gateway | backend
```

**Comment by rst-fokus** [comment]
Hello @ilovetogetspamed ,

I think it is related to some GNU tools used in the script. I will have a look to it.

Best,
Ronald

**Comment by ilovetogetspamed** [comment]
OK, thanks, let me know if  you need me to test anything.
cfo

**Comment by dnehls** [comment]
Well, "works for me" &trade; on macOS Mojave, but I remember I had to do some changes, e.g. update bash to 4.4

**Comment by ilovetogetspamed** [comment]
$ echo $BASH_VERSION
5.0.0(1)-release
$ ./create-binary-docker gateway
Error: Exactly one module name needs to be provided
Usage: create-binary-docker [OPTS] <module_name>
  OPTS:
    -a|--arch <ARCH>           Choose architecture: amd64|arm
    -p|--prefix <Name Prefix>  Choose Docker image name prefix
    -e|--export                Export the Docker image to a file, after build

    -h|--help                  Show this help
    -v|--version               Show version information

  module_name:
    gateway | backend

@dnehls any other ideas?

**Comment by dnehls** [comment]
Another issue I had was with the mac's _getopt_ 
See also [stackoverflow](https://stackoverflow.com/questions/12152077/how-can-i-make-bash-deal-with-long-param-using-getopt-command-in-mac)

**Comment by ilovetogetspamed** [comment]
@dnehls that didn't work.  Don't have time to fool with it now.  will look at it again sometime.  I tried ksh and zsh and they didn't work either.  Don't have time to waste now.  I may put it in a ubuntu vm and play with it there in the future.

**Comment by ilovetogetspamed** [comment]
FYI -- Got it going in a Ubuntu 18 VirtualBoxVM on macOS Mojave.

**Comment by ilovetogetspamed** [comment]
Update -- to run on macOS Mojave:

1) Install gnu-getopt

```
$ brew install gnu-getopt
```
2) setup your PATH to use gnu-getopt ahead of /
```
$ PATH=/usr/local/Cellar/gnu-getopt/1.1.6/bin:$PATH
$ which getopt
/usr/local/Cellar/gnu-getopt/1.1.6/bin/getopt
```
3) run the command.
```
$ ./create-binary-docker gateway
...
### Base gateway-amd64 container built successfully.
...
```

Put your path back if you like.  It will go away when you close your terminal session.  I don't recommend overriding the OS's getopt with gnu-getopt.

All is good... ;-)
