### ISSUE TITLE
[SHOULD] Every GE should have tutorial information

### ISSUE THREAD

**Issue by jason-fox** [OpenMTC/OpenMTC#19]
At the moment OpenMTC has no information in the Academy and does not minimum Training section requirements for a Full GE. This is a placeholder to ensure a simple OpenMTC hello world gets added to the Step-by-Step tutorials at some point

See https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/issues/38 as an example of compliance for an IoT Agent

* Presence of a tutorial is a SHOULD requirement it will be upgraded in the future

An incubated GE should be working to fulfilling these requirements

**Comment by aor-fokus** [comment]
Hello @jason-fox ,

I added a link to our training section inside our documentation in commit 0cdeb422f6923930fce93cf67735a84d1e057b87 
There is a Step-by-Step guide to start an IPE-Sensor,GUI-Sensor or how to use the SDK to write an "Hello World"-App.

I would say this is enough to fullfill the minimum training requirements.
What would you say?

Will add something to the academy soon.

**Comment by jason-fox** [comment]
Yes, that will do fine - could you assign this issue to me for now so it doesn't get lost, and I can link it in all the relevant places.

(It's not enough that training **exists**, it's that it must be **visible and  exist**)

**Comment by aor-fokus** [comment]
Thank you.

Assigned it to you.

**Comment by jason-fox** [comment]
@aor-fokus - I have updated the Academy and added the link box to the README. Once you process PR #33 I think this can be closed.

Of course more info added to the [academy listing](https://github.com/FIWARE/academy/blob/master/docs/iot-agents/open-mtc.md) is always welcome.

**Comment by aor-fokus** [comment]
Thanks for the PR. Merged it and close this issue now.
