### ISSUE TITLE
[SHOULD] Work towards fulfilling the requirements for a full GE

### ISSUE THREAD

**Issue by jason-fox** [OpenMTC/OpenMTC#21]
The following MUST requirements for full GE status are not currently satisfied:

Missing items within the `README`
* README - Training Section

Missing on Docker 
* DOCKER - SemVer Image Available
* DOCKER - FIWARE Image Available
* DOCKER - README present

No CREDITS file

An incubated enabler should be working to  fulfilling these requirements

* SHOULD requirement from the TSC

**Comment by aor-fokus** [comment]
Hello Jason,

I renamed our CONTRIBUTIONS file to CREDITS.
Also added our Training Section to the README.

The Docker parts are in progress now.
