### ISSUE TITLE
[MUST] Show versioned documentation

### ISSUE THREAD

**Issue by jason-fox** [OpenMTC/OpenMTC#22]
On the OpenMTC ReadtheDocs project, no versioned documentation is displayed

- Goto https://readthedocs.org/projects/fiware-openmtc/versions/
- Ensure that **active** checkmark is ticked against relevant release tags

**Comment by aor-fokus** [comment]
The active checkmark is ticked for latest,stable and now also for our last version 1.3.
Will close this now.
