### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by damsojilo** [OpenMTC/OpenMTC#28]
Im on mac  version 10.14.2, docker is installed and  i cant create a gateway image i dont know why i got this issue : 
<img width="1346" alt="capture d ecran 2019-02-11 a 16 04 26" src="https://user-images.githubusercontent.com/47530833/52571868-c58cad80-2e16-11e9-8b1b-88e1915c8c35.png">

can someone help me with this please

**Comment by Alexandero89** [comment]
Hallo damsojilo,

i think this problem was solved in Issue #16 .

Hope that helps with your problem.

**Comment by aor-fokus** [comment]
Hello damsojilo,

i think this problem was solved in Issue #16 

Hope that helps with your problem.
