### ISSUE TITLE
Support for resource type 28 (Flex Container)

### ISSUE THREAD

**Issue by Dennisparchkov** [OpenMTC/OpenMTC#3]
Is there any information about the implementation of the Flex container resource type according to the onem2m standard? 

Currently there is an issue when registering a remotecse that supports that type for example om2m. The two different implementations are not interoperable (Resource type 28 is not recognised).

**Comment by sho-fokus** [comment]
Hello @Dennisparchkov,

we do not feature support for flexcontainers at this time, nor are there (AFAIK) any particular plans to introduce such. If you would like to add this feature, you are free to register an appropriate model in [`common/openmtc-onem2m/src/openmtc_onem2m/model.py`](https://github.com/OpenMTC/OpenMTC/blob/master/common/openmtc-onem2m/src/openmtc_onem2m/model.py).

**Comment by Dennisparchkov** [comment]
Thanks for the links, i will close this issue in the meanwhile.
