### ISSUE TITLE
Gateway Notification problems: CSETargetNotReachable

### ISSUE THREAD

**Issue by CodeOne91** [OpenMTC/OpenMTC#43]
**Describe the bug**
I'm building a custom IPE for research purposes. I need to use the onem2m subscription mechanism to receive notification. 
gateway Instantiated with:
` docker run -d --name gateway -p 0.0.0.0:8000:8000 -e "LOGGING_LEVEL=DEBUG" -e "ONEM2M_NOTIFICATION_DISABLED=false" openmtc/gateway-amd64 -vv`
Notification about the example provided in the documentation not work: [https://github.com/OpenMTC/OpenMTC/blob/master/doc/subscription-notification.md](url)

Gateway generate Notification, but unable to send it to XAE application (handler),  
Gateway output provide this problem, after tha,t notification discarded: `
DEBUG:OneM2MMethodDomain:Handling CSETargetNotReachable: 
`

Is there a solution?

docker start output:
`Configuring M2M gateway...done
DEBUG:openmtc_gevent.main:Trying config file location: /config-gateway.json
DEBUG:openmtc_gevent.main:Trying config file location: /etc/openmtc/gevent/config-gateway.json
DEBUG:openmtc_gevent.main:Reading config file: /etc/openmtc/gevent/config-gateway.json
DEBUG:openmtc_gevent.main:Running OpenMTC
DEBUG:rdflib:RDFLib Version: 4.2.2
INFO:GEventNetworkManager:GEventNetworkManager loaded
DEBUG:openmtc_gevent.main:Initializing component: <openmtc_cse.transport.OneM2MTransportDomain object at 0x7f1f2ed5fef0>
DEBUG:openmtc_gevent.main:Initializing component: <openmtc_cse.methoddomain.OneM2MMethodDomain object at 0x7f1f2ed5fe48>
DEBUG:openmtc_gevent.main:Initializing component: <openmtc_gevent.GEventNetworkManager.GEventNetworkManager object at 0x7f1f2e158940>
INFO:GEventNetworkManager:GEventNetworkManager initialized
DEBUG:GEventTaskRunner:Adding task <bound method GEventNetworkManager.start_polling of <openmtc_gevent.GEventNetworkManager.GEventNetworkManager object at 0x7f1f2e158940>> to pool of size 200
DEBUG:GEventTaskRunner:Task added
INFO:GEventNetworkManager:GEventNetworkManager started
DEBUG:NoDB2Session:Adding resource to db: onem2m -> CSEBase(path='onem2m', id='cb0') (<class 'openmtc_onem2m.model.CSEBase'>)
DEBUG:NoDB2Session:parent path: 
DEBUG:NoDB2Session:No parent found
DEBUG:openmtc_onem2m.serializer.json:using simplejson for decoding JSON
WARNING:openmtc_server.platform.gevent.ServerRack:Deprecated import
DEBUG:HTTPTransportPlugin:Plugin HTTPTransportPlugin created with config {'interface': '::', 'require_cert': True, 'enable_https': False, 'onem2m': {'accept_insecure_certs': False, 'cse_type': 'MN-CSE', 'default_privileges': [{'accessControlOperations': [2, 32], 'accessControlOriginators': ['all']}], 'cse_id': 'mn-cse-1', 'overwrite_originator': {'originator': '/openmtc.org/mn-cse-1', 'enabled': False}, 'ssl_certs': {'ca': '/etc/openmtc/certs/ca-chain.cert.pem', 'crt': '/etc/openmtc/certs/mn-cse-1-client-server.cert.pem', 'key': '/etc/openmtc/certs/mn-cse-1-client-server.key.pem'}, 'sp_id': 'openmtc.org', 'cse_base': 'onem2m', 'dynamic_authorization': {'poa': [], 'enabled': False}}, 'port': 8000, 'global': {'disable_forwarding': False, 'additional_host_names': [], 'default_content_type': 'application/json', 'min_lifetime': datetime.timedelta(0, 5), 'max_lifetime': datetime.timedelta(1), 'require_auth': False, 'default_lifetime': datetime.timedelta(0, 2000)}}
INFO:openmtc_gevent.main:Plugin MQTTTransportPlugin is disabled
DEBUG:NotificationHandler:Plugin NotificationHandler created with config {'global': {'disable_forwarding': False, 'additional_host_names': [], 'default_content_type': 'application/json', 'min_lifetime': datetime.timedelta(0, 5), 'max_lifetime': datetime.timedelta(1), 'require_auth': False, 'default_lifetime': datetime.timedelta(0, 2000)}, 'onem2m': {'accept_insecure_certs': False, 'cse_type': 'MN-CSE', 'default_privileges': [{'accessControlOperations': [2, 32], 'accessControlOriginators': ['all']}], 'cse_id': 'mn-cse-1', 'overwrite_originator': {'originator': '/openmtc.org/mn-cse-1', 'enabled': False}, 'ssl_certs': {'ca': '/etc/openmtc/certs/ca-chain.cert.pem', 'crt': '/etc/openmtc/certs/mn-cse-1-client-server.cert.pem', 'key': '/etc/openmtc/certs/mn-cse-1-client-server.key.pem'}, 'sp_id': 'openmtc.org', 'cse_base': 'onem2m', 'dynamic_authorization': {'poa': [], 'enabled': False}}}
INFO:openmtc_gevent.main:Plugin ExpirationTimeHandler is disabled
INFO:openmtc_gevent.main:Plugin RegistrationHandler is disabled
INFO:openmtc_gevent.main:Plugin AnnouncementHandler is disabled
INFO:openmtc_gevent.main:Initializing plugins
INFO:HTTPTransportPlugin:Initializing plugin HTTPTransportPlugin
DEBUG:HTTPTransportPlugin:Plugin <openmtc_cse.plugins.transport_gevent_http.HTTPTransportPlugin object at 0x7f1f2dee6c18> is initialized
INFO:NotificationHandler:Initializing plugin NotificationHandler
DEBUG:NotificationHandler:Plugin <openmtc_cse.plugins.notification_handler.NotificationHandler object at 0x7f1f2dee6c88> is initialized
INFO:openmtc_gevent.main:Starting plugins
INFO:HTTPTransportPlugin:Starting plugin HTTPTransportPlugin
DEBUG:OpenMTCWSGIApplication:All listening addresses: {'172.17.0.2', '127.0.0.1'}
INFO:GEventServerRack:OpenMTCWSGIServer started on ('::', 8000, 0, 0)
DEBUG:HTTPTransportPlugin:Plugin <openmtc_cse.plugins.transport_gevent_http.HTTPTransportPlugin object at 0x7f1f2dee6c18> is started
INFO:NotificationHandler:Starting plugin NotificationHandler
DEBUG:NotificationHandler:Plugin <openmtc_cse.plugins.notification_handler.NotificationHandler object at 0x7f1f2dee6c88> is started
INFO:openmtc_gevent.main:OpenMTC is running
DEBUG:GEventNetworkManager:polling started
`

**Comment by lcoimbra** [comment]
Hello, I am having issues with the notification system as well, how did you solve this?
