### ISSUE TITLE
ImportError: cannot import name Server

### ISSUE THREAD

**Issue by janaka1984** [OpenMTC/OpenMTC#8]
Hi @ronald-steinke 

when ran ./doc/training/start-app.sh script and select  'onem2m-ipe-sensors-final.py' ,  it returned following error
ImportError: No module named iso8601
it was **solved** by running  'pip install iso8601'

after ran first script again. it returned following error
ImportError: No module named geventwebsocket.handler
it was **solved** by running  'pip install gevent-websocket'

after ran first script again. it returned following error
ImportError: No module named socketio
it was **solved** by running  'pip install socketio'

after ran first script again. it returned following error

> Traceback (most recent call last):
>   File "/home/privacy/src/OpenMTC/doc/training/apps/onem2m/ipe/sensors/onem2m-ipe-sensors-final.py", line 7, in <module>
>     from openmtc_app.onem2m import XAE
>   File "/home/privacy/src/OpenMTC/openmtc-app/src/openmtc_app/onem2m.py", line 27, in <module>
>     from openmtc_app.flask_runner import FlaskRunner
>   File "/home/privacy/src/OpenMTC/openmtc-app/src/openmtc_app/flask_runner/__init__.py", line 8, in <module>
>     from socketio import Server as SioServer, Middleware as SioMiddleware
> ImportError: cannot import name Server

give me hint to solve this

Regards
Janaka

**Comment by rst-fokus** [comment]
There seem to be a problem with dependencies. How are you using it? I guess you are running it from terminal directly.

Just run from within the repo "pip install -r openmtc-gevent/dependencies.txt" to install all necessary dependencies.

**Comment by janaka1984** [comment]
Hi @rst-fokus 

the problem is solved after installed dependencies.  thanks 

Regards
Janaka
